clocktime: 30

cardcsm:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11

sp:
  1: #1~11ドロー系
    enable: true
    csm: 0
  2: #
    enable: false
    csm: 0



tipcoin: 10
round: 3
