mysql: # DB
  host: localhost
  user: root
  pass: pass
  port: 3306
  db: 21

cardcsm: # ノーマルカードのtex
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11

sp:
  1: # 1~11ドロー系
    enable: true #有効か無効か
    csm: 0 #これだけ0固定
    drawcsm:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11

  2: #リムーブ
    enable: true
    csm: 0

  3: #デストロイ
    enable: true
    csm: 0

  4:
    enable: true
    csm: 0

  5:
    enable: true
    csm: 0
  6:
    enable: true
    csm: 0

  7:
    enable: true
    csm: 0

  8: #ベットアップ1
    enable: true
    csm: 0

  9: #ベットアップ2
    enable: true
    csm: 0

  10:
    enable: true
    csm: 0

  11:
    enable: true
    csm: 0

  12:
    enable: true
    csm: 0

  13:
    enable: true
    csm: 0

  14:
    enable: true
    csm: 0

  15:
    enable: true
    csm: 0

  16:
    enable: true
    csm: 0

  17:
    enable: true
    csm: 0

  18:
    enable: true
    csm: 0

  19:
    enable: true
    csm: 0

  20:
    enable: true
    csm: 0

  21:
    enable: true
    csm: 0

  22:
    enable: true
    csm: 0


tipcoin: 10 #初期チップ
round: 3 #ラウンド数
clocktime: 30 #時計の時間
firstbet: 2 #初期ベッド


switch:
  savemode: false
  mode: true